stages:
  - name: deploy
    if: tag IS blank

language: go
go:
- '1.11'

env:
  global:
    - VERSION="v0.0.${TRAVIS_BUILD_NUMBER}"
    - secure: "SZVfZ64xoCD//P1JAFL4tYqy7cxCxdJ7ahkn8IZ/vg/o1W2LkBhUjmZb2NW5ltZmK148a/goZx0BL58pLEcOGMRjA4BpeFqdrZlcOAUBCadkBboc/8iPzxAnZt9eqad0E0K8pKHFA7tQaQCkDMSkSENsh/+ALkXzUnP9CUVUkr76zyd5AZ3Bj6keeojas9n8FgaGHrERo2n2VhYYlr0b0BR/cfBSuVvmUQjLqljZME9U1WOIVn5RXY1by+uh90MlDuGw9H5MEBfywiLyd3wGTxmy6dCFFIqDxvH53w6uEpHfOj8jHukuMOFRnDOHT+8TKDF6QmBfZPjfQcj2DC8yuIB0bOKokUZ0vLEpb2quzIetBbvOdPuVdIu9UQE7mUOJmeaZdJeW2criczn6LfO7QcoBrqBLpjcqawXIXdeappv00JwxCwnbVmqj7dnJrAsUQML0x0UxXmfFzwjt4SbABdYxlOKwv9vkzfIbQLT3uZVUH+wunfwG6RxIMMJVNzwN8oibh7QURbDWv/2wEImt0e0pM841PZ/mlY8cgufwSB2+1FIofOz77qY9/4k7eZD0l1cwqu93LEJzBSBeXPNcXjeXPx8WEQDpTsOd3zlvxZhjzLPsiifI7+xQxT+i3c1afhopStYH/G+KlbeNpjJS6v6kA5yD4LFCguZ3wxMTVy4="

before_install:
- go get github.com/mitchellh/gox

install:
- go get -t -v ./...

script:
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
- gox -os="darwin" -arch="amd64" -output="doo.{{.OS}}.{{.Arch}}" -ldflags "-X main.version=${VERSION}" -verbose ./...

after_success:
- echo "$VERSION"  
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag -a "${VERSION}" -m "${VERSION}"
- git push https://$GITHUBKEY@github.com/gekalogiros/Doo --tags

deploy:
  provider: releases
  api_key:
    secure: c6OTcQ6ej+osUwuQlFBaioM+LA2nJgkCrF1elKX8FlRgFgq0wKPEDoSprUXw7Oefx017Z0UYH9Wc2ZbojvNZWCfDDV/6Jw3BTytUJ/QN/0rmXTD44o4UypPXWYmP3Y7xILhuJ7+OnBIgUJM+vbHiC+aQbKipVJ+K0FiJ4phV7VEfjkWm7CFtJqAYvMpikqC5KLUAxNupjdFlAjdIKEhyQdRHLqH1Cn8musZ8o/XEtFQvg/lUfLUrsAlaHj0hev6JDshxFRW1+N4yuU/o4bi7SsSiPVqE7rkGvcEsZCryODod3MCE/ROSeW4yUl7KOfz6mpov68tma0t+Dm6PzRT8vsXnZtswWI2DbvEg6bTxvFKFQ1/YHB0Kfhif2JaIcaGAd1RgtWEJ+71z3+CHvj39tio1YTqpaW0duDt68DgTfv79n137cjP/xxZG/8ueuHssuhYAGRZm8dAJ7Bu9dItxxUBqFY2+N97vNYGYAFBRt0ODleykofzrL0FHOnN9UCboKV3D6fQMwQLbTw0yC2Z5GtBkY1nM88LXB5/dGzuk+QfooHbXR5DRaPK3+HCbDGf4yFSftPz7HPt8QcBugy8Oo71rodvPNLvMr61HASyiBxgGOLc7caIhLTShvXow66WsbeVkVJ0RbHbCCfX5cWVu1iLPlT04N7/qDjttLpj7OQg=
  file: doo.darwin.amd64
  skip_cleanup: true
  on:
    repo: gekalogiros/Doo
    tags: true
