language: go
go:
- '1.11'

before_install:
  - go get github.com/mitchellh/gox

install:
  - go get -t -v ./...

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - gox -os="darwin" -arch="amd64" -output="doo.{{.OS}}.{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...

deploy:
  provider: releases
  api_key:
    secure: c6OTcQ6ej+osUwuQlFBaioM+LA2nJgkCrF1elKX8FlRgFgq0wKPEDoSprUXw7Oefx017Z0UYH9Wc2ZbojvNZWCfDDV/6Jw3BTytUJ/QN/0rmXTD44o4UypPXWYmP3Y7xILhuJ7+OnBIgUJM+vbHiC+aQbKipVJ+K0FiJ4phV7VEfjkWm7CFtJqAYvMpikqC5KLUAxNupjdFlAjdIKEhyQdRHLqH1Cn8musZ8o/XEtFQvg/lUfLUrsAlaHj0hev6JDshxFRW1+N4yuU/o4bi7SsSiPVqE7rkGvcEsZCryODod3MCE/ROSeW4yUl7KOfz6mpov68tma0t+Dm6PzRT8vsXnZtswWI2DbvEg6bTxvFKFQ1/YHB0Kfhif2JaIcaGAd1RgtWEJ+71z3+CHvj39tio1YTqpaW0duDt68DgTfv79n137cjP/xxZG/8ueuHssuhYAGRZm8dAJ7Bu9dItxxUBqFY2+N97vNYGYAFBRt0ODleykofzrL0FHOnN9UCboKV3D6fQMwQLbTw0yC2Z5GtBkY1nM88LXB5/dGzuk+QfooHbXR5DRaPK3+HCbDGf4yFSftPz7HPt8QcBugy8Oo71rodvPNLvMr61HASyiBxgGOLc7caIhLTShvXow66WsbeVkVJ0RbHbCCfX5cWVu1iLPlT04N7/qDjttLpj7OQg=
  file: doo.darwin.amd64
  skip_cleanup: true
  on:
    repo: gekalogiros/Doo
    tags: true
