language: go
go:
- '1.11'
env:
  secure: IhtngPvC7yyPQF4AnhMnF3nbPEbNMObH2ysSRsKvMdX//HjW8sCcjKJsZ3tsV486xlWkJzRK0LdR5rZKhZAq8yZE1Fj1EsYUMpllK5wzgIRCfAqJGBULeaL2Zo2VHm+rPQC2mHkwpWoM4g4yMJbJrR/Xzh0i2SYj1z3ip5KMjGV4s3wFoBTloKCtFaCW0T1LwTRedkak9OTnAv154gEqkqcO18HQmitsGZ8OGhNPalSuAT5NXhk0RosDCtLnuDvlmQx98FKn+FPhU0YGwlxLgpiFRvsFIhceMx3IMX+Z6CTJL0HX/q39iDJ4wfR4wPWfvfF4+utjbrQuuuPZ1VGVaST3FNGFjF72IVduqk3mtzcYhgGuwMypH01YMHjPQtewRmi0g7mL7gyyzTy+lxtQy4LJojWoyqQLPkJjuLhDnnc/quqYxHJiGGqrkBPV60tW+sAR5HacrgAHW8b4nZlIpj8Lqo7L8SEJVvQN77ZC7ot/G0g1YbTTU1eTYQl+J2g3sn9bG/blyxSO4PLNckiYPXUggrseUDuKSEBQrNSpzol5RLJhHmvvVlzvPbZ5j9N+BEG6Y8WxSLofPKHZHPQuo8bGn7fmZxpyDH1pya5z502KMjN97NwfWmQ0asqReVm1pbyGG9noqyXJZnGhUaGtF4iL6y4egc3FvtFwB8LFDsk=
before_install:
- go get github.com/mitchellh/gox
install:
- go get -t -v ./...
script:
- go vet $(go list ./... | grep -v /vendor/)
- go test -v -race ./...
- gox -os="darwin" -arch="amd64" -output="doo.{{.OS}}.{{.Arch}}" -ldflags "-X main.version=${VERSION}"
  -verbose ./...
defore_deploy:
- git config --local user.name "gekalogiros"
- git config --local user.email "foo@foo.com"
- git tag "${VERSION}" "${TRAVIS_COMMIT}"
deploy:
  provider: releases
  api_key:
    secure: c6OTcQ6ej+osUwuQlFBaioM+LA2nJgkCrF1elKX8FlRgFgq0wKPEDoSprUXw7Oefx017Z0UYH9Wc2ZbojvNZWCfDDV/6Jw3BTytUJ/QN/0rmXTD44o4UypPXWYmP3Y7xILhuJ7+OnBIgUJM+vbHiC+aQbKipVJ+K0FiJ4phV7VEfjkWm7CFtJqAYvMpikqC5KLUAxNupjdFlAjdIKEhyQdRHLqH1Cn8musZ8o/XEtFQvg/lUfLUrsAlaHj0hev6JDshxFRW1+N4yuU/o4bi7SsSiPVqE7rkGvcEsZCryODod3MCE/ROSeW4yUl7KOfz6mpov68tma0t+Dm6PzRT8vsXnZtswWI2DbvEg6bTxvFKFQ1/YHB0Kfhif2JaIcaGAd1RgtWEJ+71z3+CHvj39tio1YTqpaW0duDt68DgTfv79n137cjP/xxZG/8ueuHssuhYAGRZm8dAJ7Bu9dItxxUBqFY2+N97vNYGYAFBRt0ODleykofzrL0FHOnN9UCboKV3D6fQMwQLbTw0yC2Z5GtBkY1nM88LXB5/dGzuk+QfooHbXR5DRaPK3+HCbDGf4yFSftPz7HPt8QcBugy8Oo71rodvPNLvMr61HASyiBxgGOLc7caIhLTShvXow66WsbeVkVJ0RbHbCCfX5cWVu1iLPlT04N7/qDjttLpj7OQg=
  file: doo.darwin.amd64
  skip_cleanup: true
  on:
    repo: gekalogiros/Doo
    tags: true
